/**
 * Nocturn Preset Themes Configuration
 * Shared theme objects ready for database persistence.
 */

export const DEFAULT_NOCTURN_THEME = {
  id: 'preset-nocturn-green',
  name: 'Nocturn Green',
  isPreset: true,
  userId: null,
  colors: {
    background: '#000000',
    surface: '#0B120D',
    elevated: '#101A13',
    accent: '#00E676',
    accentGlow: '#69F0AE',
    text: '#FFFFFF',
    textSecondary: '#A7B3AA',
    border: '#18261C',
    overdue: '#EF4444',
    today: '#3B82F6',
    tomorrow: '#EAB308',
    future: '#00E676',
  },
}

export const PRESET_THEMES = [
  DEFAULT_NOCTURN_THEME,
  {
    id: 'preset-midnight-blue',
    name: 'Midnight Blue',
    isPreset: true,
    userId: null,
    colors: {
      background: '#090D16',
      surface: '#0F172A',
      elevated: '#1E293B',
      accent: '#38BDF8',
      accentGlow: '#7DD3FC',
      text: '#F8FAFC',
      textSecondary: '#94A3B8',
      border: '#1E293B',
      overdue: '#F87171',
      today: '#38BDF8',
      tomorrow: '#FACC15',
      future: '#4ADE80',
    },
  },
  {
    id: 'preset-crimson',
    name: 'Crimson',
    isPreset: true,
    userId: null,
    colors: {
      background: '#0D0709',
      surface: '#1A0F13',
      elevated: '#26161D',
      accent: '#FF2A5F',
      accentGlow: '#FF6B8B',
      text: '#FFFFFF',
      textSecondary: '#A38F97',
      border: '#2A1720',
      overdue: '#EF4444',
      today: '#3B82F6',
      tomorrow: '#EAB308',
      future: '#FF2A5F',
    },
  },
  {
    id: 'preset-amber',
    name: 'Amber',
    isPreset: true,
    userId: null,
    colors: {
      background: '#0D0B07',
      surface: '#1A160E',
      elevated: '#292215',
      accent: '#F59E0B',
      accentGlow: '#FCD34D',
      text: '#FFFFFF',
      textSecondary: '#B8AA94',
      border: '#2D2315',
      overdue: '#EF4444',
      today: '#3B82F6',
      tomorrow: '#F59E0B',
      future: '#10B981',
    },
  },
  {
    id: 'preset-warm-amber',
    name: 'Warm Amber',
    isPreset: true,
    userId: null,
    colors: {
      background: '#0A0908',
      surface: '#141210',
      elevated: '#1F1C18',
      accent: '#F59E0B',
      accentGlow: '#FBBF24',
      text: '#FAF8F5',
      textSecondary: '#A8A29E',
      border: '#2E271F',
      overdue: '#EF4444',
      today: '#F59E0B',
      tomorrow: '#FBBF24',
      future: '#F59E0B',
    },
  },
]
